name: Tests
on: push
jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3
      - name: Use Node.js 12
        uses: actions/setup-node@v2
        with:
          node-version: 12
          check-latest: true
      - name: Install dependencies
        run: yarn install --immutable
      - name: Lint
        run: yarn lint
